// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const mode = process.env.MODE === "offline" ? "offline" : "online";

export default defineConfig({
  schema: mode === "offline" ? "prisma/schema.sqlite.prisma" : "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      mode === "offline"
        ? process.env.SQLITE_DATABASE_URL ?? "file:./data/school.db"
        : process.env.DATABASE_URL,
  },
});
