{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openwa.fullname" . }}
  labels:
    {{- include "openwa.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openwa.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.bearerTokenSecret.name }}
      bearerTokenSecret:
        name: {{ .Values.serviceMonitor.bearerTokenSecret.name }}
        key: {{ .Values.serviceMonitor.bearerTokenSecret.key }}
      {{- end }}
{{- end }}
