apiVersion: v2
name: openwa
description: OpenWA — WhatsApp API. Single-instance StatefulSet (see values.yaml replicaCount warning).
type: application
version: 0.1.1
appVersion: "0.13.0"
keywords:
  - whatsapp
  - openwa
  - api
home: https://github.com/rmyndharis/OpenWA
sources:
  - https://github.com/rmyndharis/OpenWA
